deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="
  region: "us-east-1"
  app: "Live Style Guide"
  env: "util-live-style-guide"
  bucket_name: "elasticbeanstalk-us-east-1-883361901652"

